### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by trebmuh** [anthem-audio/Anthem#59]
Hi, I've been trying this software today. It does look to compile fine (I didn't see anything wrong while doing so), but it doesn't run when launched from the terminal. The error message is:
```
QQmlApplicationEngine failed to load component
qrc:/main.qml:80 Expected token `numeric literal'
qrc:/main.qml:80 Unexpected token `>'
qrc:/main.qml:81 Expected token `:'
qrc:/main.qml:81 Expected token `}'
```

PS: Debian buster up-to-date here

**Comment by grejppi** [comment]
Please note that we are at a very early stage of development; so far this repository has only the UI that is missing most functionality, and the audio engine has not been merged in yet. There's really no support at this point, or any expectation of being usable.

Anyway: we are targeting the latest version of Qt (currently 5.14), and as far as I can tell buster has only 5.11, which doesn't support the new ES6 syntax and certain components used in our QML files.

**Comment by trebmuh** [comment]
OK, thanks for your quick answer. I'll wait a bit then.
